name = "Registry"
uuid = "ae0cb698-197b-42ec-a0a0-4f871aea6013"
repo = "https://github.com/fredrikekre/Registry.git"

[packages]
13b54a02-2f9f-4836-8d63-2896159f488f = { name = "ImportMacros", path = "I/ImportMacros" }
